name: Dev DNS health check

on:
  workflow_dispatch:
  # schedule:
  #  - cron:  '0 * * * *'

jobs:
  run_test:
    name: Some more fancy name
    runs-on: ubuntu-latest
    env:
      dns_name: "skf.coewwerwerm"
      dns_resolver: "8.8.8.8"
      dns_resolver_name: "Google"
    steps:
      - uses: actions/checkout@v3
      - name: Try to resolve DNS name google.com
        run: |
          nslookup $dns_name
          dig $dns_name
      - name: Send alert if an error occurred
        if: failure()
        run: >
          curl -X POST https://hooks.slack.com/triggers/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
          -H "Content-Type: application/json; charset=utf-8"
          -d '{"dns_name":"${{ env.dns_name }}","dns_resolver":"${{ env.dns_resolver }}","dns_resolver_name":"${{ dns_resolver_name }}"}'
